ozone/blueprints/column.py
from flask import Blueprint, render_template, abort, g, request, redirect, url_for, session
from flask import current_app as app
from jinja2 import TemplateNotFound
import sqlite3
import time
from reminder_util import EmailReminder 
from config import logger

column_page = Blueprint("column", __name__, template_folder="templates")

def connect_db():
    logger.info("Connect to database...")

    rv = sqlite3.connect(app.config['DATABASE'])
    rv.row_factory = sqlite3.Row
    return rv

def get_db():
    if not hasattr(g, 'sqlite3_db'):
        g.sqlite_db = connect_db()
    return g.sqlite_db

def close_db():
    if hasattr(g, 'sqlite3_db'):
        logger.info("Closing database...")
        g.sqlite_db.close()

@column_page.route('/<title>/<int:page>')
def show_essay(title, page=1):
    if "logged_in" not in session:
        return redirect(url_for("login"))

    with app.app_context():
        db = get_db()
        num_per_page = app.config['COLUMN_PER_PAGE']
        # get all the titles
        cur = db.cursor().execute("select distinct title from essay order by timestamp desc")
        titles = [row[0] for row in cur.fetchall()]
        logger.debug("All the titles:\n{}".format(titles))

        if (title == "all"):
            logger.debug("Title is all")

            # get total num of essays
            cur = db.cursor().execute("select count(*) from essay")
            num = cur.fetchall()[0][0]
            if (num % num_per_page == 0):
                max_page = int(num / num_per_page)
            else:
                max_page = int((num / num_per_page) + 1)
            logger.debug("Total num of message is {}, max_page is {}".format(num, max_page))

            if ((page - 1) * num_per_page >= num):
                logger.warning("Illegal page number: {}".format(page))
                page = max_page

            if (page <= 0):
                logger.warning("Illegal page number: {}".format(page))
                page = 1

            cur = db.cursor().execute("select timestamp, owner, title, content from essay order by timestamp desc limit ? offset ?", [num_per_page, (page - 1) * num_per_page])
            essays = [dict(timestamp=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(row[0])), owner=row[1], title=row[2], content=row[3], collapse_id=row[0]) for row in cur.fetchall()]
            logger.debug("Essays:\n{}".format(essays))
        else:
            logger.debug("Title is {}".format(title))
            cur = db.cursor().execute("select count(*) from essay where title = ?", [title])
            num = cur.fetchall()[0][0]
            if (num % num_per_page == 0):
                max_page = int(num / num_per_page)
            else:
                max_page = int((num / num_per_page) + 1)
            logger.debug("Total num of message is {}, max_page is {}".format(num, max_page))

            if ((page - 1) * num_per_page >= num):
                logger.warning("Illegal page number: {}".format(page))
                page = max_page

            if (page <= 0):
                logger.warning("Illegal page number: {}".format(page))
                page = 1

            cur = db.cursor().execute("select timestamp, owner, title, content from essay where essay.title = ? order by timestamp desc limit ? offset ?", [title, num_per_page, (page - 1) * num_per_page])
            essays = [dict(timestamp=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(row[0])), owner=row[1], title=row[2], content=row[3], collapse_id=row[0]) for row in cur.fetchall()]
            logger.debug("Essays:\n{}".format(essays))
        close_db()
        try:
            return render_template("show_essay.html", essays=essays, total_page=max_page, current_page=page, titles=titles, current_title=title)
        except TemplateNotFound:
            logger.error("Template not found")
            abort(404)

@column_page.route('/add', methods=['POST'])
def add_essay():
    owner = None

    # check if log in
    if "logged_in" not in session:
        return redirect(url_for("login"))

    # start add message
    with app.app_context():
        db = get_db()
        timestamp = int(time.time())
        if session["logged_user"] == "wang":
            owner = "汪先森"
        elif session["logged_user"] == "miao":
            owner = "小笨笨"
        else:
            logger.error("Invalid username, something goes wrong!!!")

        logger.debug("Added title is:\n{}\nContent is:\n{}".format(request.form["title"], request.form["content"]))

        db.cursor().execute("insert into essay (timestamp, owner, title, content, user1_read, user2_read) values (?, ?, ?, ?, 0, 0)", [timestamp, owner, request.form["title"], request.form["content"]])
        db.commit()
        close_db()

        # email reminder
        if (owner == "汪先森"):
            receiver = app.config['USER2_MAILADDRESS']
            receiver_name = app.config['USERNAME2']
        elif (owner == "小笨笨"):
            receiver = app.config['USER1_MAILADDRESS']
            receiver_name = app.config['USERNAME1']
        else:
            logger.error("Invalid username, something goes wrong!!!")
        message_content = "An essay has been updated, go and have a look~"

        reminder = EmailReminder(app.config['MAIL_SERVER'], app.config['MAIL_PORT'], app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'], False)
        try:
            reminder.send(receiver, receiver_name, message_content)
        except:
            logger.warning("Send email failure")

    try:
        return redirect(url_for("column.show_essay", title="all", page=1))
    except TemplateNotFound:
        logger.error("Template not found")
        abort(404)

ozone/blueprints/message.py
from flask import Blueprint, render_template, abort, g, request, redirect, url_for, session
from flask import current_app as app
from jinja2 import TemplateNotFound
import sqlite3
import time
from reminder_util import EmailReminder
from config import logger

message_page = Blueprint("message", __name__, template_folder="templates")

def connect_db():
    logger.info("Connect to database...")

    rv = sqlite3.connect(app.config['DATABASE'])
    rv.row_factory = sqlite3.Row
    return rv

def get_db():
    if not hasattr(g, 'sqlite3_db'):
        g.sqlite_db = connect_db()
    return g.sqlite_db

def close_db():
    if hasattr(g, 'sqlite3_db'):
        logger.info("Closing database...")
        g.sqlite_db.close()

@message_page.route('/<int:page>')
def show_message(page=1):
    if "logged_in" not in session:
        return redirect(url_for("login"))

    with app.app_context():
        db = get_db()
        num_per_page = app.config['MESSAGE_PER_PAGE']

        # get total num of messages
        cur = db.cursor().execute("select count(*) from message")
        num = cur.fetchall()[0][0]
        if (num % num_per_page == 0):
            max_page = int(num / num_per_page)
        else:
            max_page = int((num / num_per_page) + 1)

        logger.debug("Total num of message is {}, max_page is {}".format(num, max_page))
        
        if ((page - 1) * num_per_page >= num):
            logger.warning("Illegal page number: {}".format(page))
            page = max_page

        if (page <= 0):
            logger.warning("Illegal page number: {}".format(page))
            page = 1

        cur = db.cursor().execute("select timestamp, owner, content from message order by timestamp desc limit ? offset ?", [num_per_page, (page - 1) * num_per_page])
        messages = [dict(timestamp=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(row[0])), owner=row[1], content=row[2]) for row in cur.fetchall()]
        logger.debug("Messages are:\n{}".format(messages))
        close_db()
        try:
            return render_template("show_message.html", messages=messages, total_page=max_page, current_page=page)
        except TemplateNotFound:
            logger.error("Template not found")
            abort(404)

@message_page.route('/add', methods=['POST'])
def add_message():
    owner = None

    # check if log in
    if "logged_in" not in session:
        return redirect(url_for("login"))

    # start add message
    with app.app_context():
        db = get_db()
        timestamp = int(time.time())
        if session["logged_user"] == "wang":
            owner = "汪先森"
        elif session["logged_user"] == "miao":
            owner = "小笨笨"
        else:
            logger.error("Invalid username, something goes wrong!!!")

        db.cursor().execute("insert into message (timestamp, owner, content) values (?, ?, ?)", [timestamp, owner, request.form["content"]])
        db.commit()
        close_db()

        # email reminder
        if (owner == "汪先森"):
            receiver = app.config['USER2_MAILADDRESS']
            receiver_name = app.config['USERNAME2']
        elif (owner == "小笨笨"):
            receiver = app.config['USER1_MAILADDRESS']
            receiver_name = app.config['USERNAME1']
        else:
            logger.error("Invalid username, something goes wrong!!!")

        message_content = "A new message for you, go and have a look~"
        reminder = EmailReminder(app.config['MAIL_SERVER'], app.config['MAIL_PORT'], app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'], False)
        try:
            reminder.send(receiver, receiver_name, message_content)
        except:
            logger.warning("Send email failure")

        try:
            return redirect(url_for("message.show_message", page=1))
        except TemplateNotFound:
            logger.error("Template not found")
            abort(404)

ozone/templates/add_album.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <div class="card">
        <h2 class="card-title">新建相册</h2>
        <div class="card-body">
            <form action="{{ url_for('album.add_album') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">名称</span>
                    </div>
                    <input type="text" class="form-control" id="title" name="title" placeholder="name">
                </div>
                     
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">描述</span>
                    </div>
                    <input type="text" class="form-control" id="title" name="about" placeholder="可不填">
                </div>

                <div class="mx-auto">
                    <button type="submit" class="btn btn-primary btn-lg">提交</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ozone/templates/add_essay.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid">
    <form action="{{ url_for('column.add_essay') }}" method="post" class="add-essay">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <input type="text" id="title" name="title" class="form-control" placeholder="#title">
            <br>
            <textarea class="form-control" id="content" name="content"></textarea>
            <br>
        </div>
        <div class="float-right">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </form>
</div>
{% endblock %}

ozone/templates/add_message.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid">
    <form action="{{ url_for('message.add_message') }}" method="post" class="add-message">
        {{ form.hidden_tag() }}
        <div class="form-group">
            <textarea class="form-control" id="content" name="content" placeholder="说些什么吧..."></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-lg float-right">提交</button>
    </form>
</div>
{% endblock %}

ozone/templates/base.html
<!doctype html>
<html lang="zh-CN">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='AudioPlayer/css/audioplayer.css') }}" />
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<style>
	.navbar {
		margin-bottom: 0px;
	}

	.jumbotron {
		background: linear-gradient(#FFC0CB, #EE82EE);
	}

	.exhibition {
		margin:5px;
		-webkit-box-shadow: inset 0 1px 0 rgba( 255, 255, 255, .15 ), 0 0 1.25em rgba( 0, 0, 0, .5 ); /* 20 */
		-moz-box-shadow: inset 0 1px 0 rgba( 255, 255, 255, .15 ), 0 0 1.25em rgba( 0, 0, 0, .5 ); /* 20 */
		box-shadow: inset 0 1px 0 rgba( 255, 255, 255, .15 ), 0 0 1.25em rgba( 0, 0, 0, .3 ); /* 20 */
	}

	.exhibition img {
		display: block;
		border: 0;
		width: 100%;
	}

	.avatar {
		display: block;
		width: 300px;
		margin: 5px;
	}
	
	.avatar img {
		display: block;
		border: 0;
		width: 100%;
		transform: scale(1);
		transition: all 1s ease 0s;
		-webkit-transform: scale(1);
		-webkit-transform: all 1s ease 0s;
		border-radius: 2px;
	}
	
	.avatar:hover img {
		transform: scale(1.1);
		transition: all 1s ease 0s;
		-webkit-transform: scale(1.1);
		-webkit-transform: all 1s ease 0s;
	}

	body {
		background-color:#EEE9E9;
	}
</style>

<body>
	{% if session.logged_in %}
	<nav class="navbar navbar-expand-md bg-light navbar-light">
		<a class="navbar-brand" href="#">Ozone</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('main.index') }}">主页</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('message.show_message', page=1) }}">留言</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('column.show_essay', title='all', page=1) }}">专栏</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('album.show_photo') }}">相册</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">管理</a>
					<div class="dropdown-menu">
						<a href="{{ url_for('main.manage', function='message') }}" class="dropdown-item">留言</a>
						<div class="dropdown-divider"></div>
						<a href="{{ url_for('main.manage', function='column') }}" class="dropdown-item">专栏</a>
						<div class="dropdown-divider"></div>
						<a href="{{ url_for('main.manage', function='album') }}" class="dropdown-item">相册</a>
					</div>
				</li>
			</ul>
			<ul class="navbar-nav float-right">
				<li class="nav-item"><a class="nav-link" href="{{ url_for('main.logout') }}">注销</a></li>
			</ul>
		</div>
	</nav>
	{% endif %}
	{% for message in get_flashed_messages(with_categories=True) %}
	<div class="alert alert-{{ message[0] }} alert-dismissable fade show">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<strong>{{ message[1] }}</strong>
	</div>  
	{% endfor %}
	{% block body %}{% endblock %}
</body>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tinymce_setup.js') }}"></script>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
<script src="{{ url_for('static', filename='AudioPlayer/js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='AudioPlayer/js/audioplayer.js') }}"></script>
<script>
	$(function() {
		$('audio').audioPlayer();
	});
</script>

<br>
<br>
<br>
<br>
<br>
<br>
<footer>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom justify-content-center">
		<a class="navbar-brand" href="{{ url_for('main.index') }}">Ozone</a>
		<span class="navbar-text">
			Made by Wen Copyright&copy; 2018. All rights reserved. 
		</span>
	</nav>
</footer>

</html>

ozone/templates/column_manage.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <div class="table-responsive-md">
        <table class="table table-sm table-hover">
            <thead>
                <tr class="row mx-0">
                    <th class="col-3">
                        <h4>标题</h4>
                    </th>
                    <th class="col-3">
                        <h4>内容</h4>
                    </th>
                    <th class="col-3">
                        <h4>日期</h4>
                    </th>
                    <th class="col-3">
                        <h4>操作</h4>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for essay in essays %}
                    <tr class="row mx-0">
                        <td class="col-3">
                            <h6>{{ essay.title }}</h6>
                        </td>
                        <td class="col-3">
                            <h6>{{ essay.content|striptags|my_truncate(40) }}</h6>
                        </td>
                        <td class="col-3">
                            <h6>{{ essay.timestamp|my_timefmt }}</h6>
                        </td>
                        <td class="col-3">
                            <a href="{{ url_for('column.update', timestamp=essay.timestamp) }}" class="btn btn-sm btn-primary" role="button">修改</a>
                            <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#myModal_{{ essay.timestamp }}">删除</button>
                            <div class="modal fade" id="myModal_{{ essay.timestamp }}">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <!-- 模态框头部 -->
                                        <div class="modal-header">
                                            <div class="d-flex justify-content-center">
                                                <h3>NOTICE</h3>
                                            </div> 
                                        </div>
                               
                                        <!-- 模态框主体 -->
                                        <div class="modal-body">
                                            <div class="d-flex justify-content-center">
                                                <h4>删除后无法恢复，请谨慎操作</h4>
                                            </div>
                                            <div class="d-flex justify-content-around">
                                                <a href="{{ url_for('column.delete', timestamp=essay.timestamp) }}" class="btn btn-lg btn-danger" role="button">确认删除</a>
                                                <button type="button" class="btn btn-lg btn-primary" data-dismiss="modal">不，手抖按错了</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

ozone/templates/login.html
<!doctype html>
<html lang="zh-CN" xmlns:link="http://www.w3.org/1999/XSL/Transform">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{{ url_for('static', filename='lib/bootstrap-4.3.1/css/bootstrap.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='AudioPlayer/css/audioplayer.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
	<link rel="shortcut icon" href="{{ url_for('static', filename='imgs/favicon.ico') }}">
    <title>Login</title>
</head>

<body style="background-color: #CCCCCC;">
    <div>
        <br>
    </div>
    <div class="container">
        <div class="card login">
            <div class="card-header">
                <br>
                <h3>SIGN UP</h3>
                <br>
            </div>
            <div class="card-body">
                <form class="form" action="{{ url_for('main.login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <br>
                    <div class="form-group">
                        <input type="text" class="form-control" id="username" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary btn-login">登录</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{{ url_for('static', filename='tinymce/js/tinymce/tinymce.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tinymce_setup.js') }}"></script>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.5/umd/popper.min.js"></script>
<script src="{{ url_for('static', filename='lib/bootstrap-4.3.1/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='AudioPlayer/js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='AudioPlayer/js/audioplayer.js') }}"></script>
<script>
	$(function() {
		$('audio').audioPlayer();
	});
</script>

<br>
<br>
<br>
<br>
<br>
<br>
<footer>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-bottom justify-content-center">
		<a class="navbar-brand" href="{{ url_for('main.index') }}">Ozone</a>
		<span class="navbar-text">
			Made by Wen Copyright&copy; 2018-2019. All rights reserved.
		</span>
	</nav>
</footer>

</html>

ozone/templates/photo_upload.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <form action="{{ url_for('album.upload_photo', title=title) }}" method="post" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <input type="file" name="file" multiple="multiple">
                <button type="submit" class="btn btn-primary float-right">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

ozone/templates/show_essay.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-10 offset-sm-1 col-md-6 offset-md-3" style="border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;">
			<a href="{{ url_for('column.add_essay') }}" role="button" class="btn btn-lg btn-primary">新建专栏</a>
			{% for essay in essays %}
			{% if essay.owner == "汪先森" %}
			<div class="card">
				<div id="{{ essay.collapse_id }}">
					<div class="card-body">
						<h1 class="card-title">{{ essay.title }}</h4>
						{{ essay.content|safe|my_str_filter }}
					</div>
				</div>
				<div class="card-footer text-right" style="background:linear-gradient(to right, rgba(135, 206, 250, 1), rgba(135, 206, 250, 0.6));">
					{{ essay.timestamp }} by {{ essay.owner }}
				</div>
			</div>
			{% elif essay.owner == "小笨笨" %}
			<div class="card">
				<div id="{{ essay.collapse_id }}">
					<div class="card-body">
						<h1 class="card-title">{{ essay.title }}</h4>
						{{ essay.content|safe|my_str_filter }}
					</div>
				</div>
				<div class="card-footer text-right" style="background: linear-gradient(to right, rgba(255, 192, 203, 1), rgba(255, 192, 203, 0.6));">
					{{ essay.timestamp }} by {{ essay.owner }}
				</div>
			</div>
			{% else %}
			<li><em>No messages</em>
				{% endif %}
				<br>
				{% endfor %}

				<!--pagination-->
				<div class="d-flex justify-content-center">
					<ul class="pagination">
						<li class="page-item"><a class="page-link" href="{{ url_for('column.show_essay', title=current_title, page=current_page-1) }}">&laquo;</a></li>
						{% for page in range(1, total_page + 1) %}
						{% if current_page == page %}
						<li class="page-item active"><a class="page-link" href="{{ url_for('column.show_essay', title=current_title, page=page) }}">{{ page }}</a></li>
						{% else %}
						<li class="page-item"><a class="page-link" href="{{ url_for('column.show_essay', title=current_title, page=page) }}">{{ page }}</a></li>
						{% endif %}
						{% endfor %}
						<li class="page-item"><a class="page-link" href="{{ url_for('column.show_essay', title=current_title, page=current_page+1) }}">&raquo;</a></li>
					</ul>
				</div>
		</div>
		<div class="col-sm-auto col-md-3" style="margin-top: 50px;background: linear-gradient(#FFC0CB, #EE82EE);">
			<h3>我们的足迹</h3>
			<nav class="sidebar">
				<div class="sidebar-sticky">
					<ul class="nav flex-column">
					{% for t in titles %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('column.show_essay', title=t, page=1) }}"><h4>{{ t }}</h4></a></li>
					{% endfor %}
					</ul>
				</div>
			</nav>
		</div>
		<div class="col-sm-10 offset-sm-1 col-md-6 offset-md-3" style="margin-top: 20px;">
			<div class="dropdown">
				<button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown">
					我们的足迹
				</button>
				<div class="dropdown-menu">
					{% for t in titles %}
					<a class="dropdown-item" href="{{ url_for('column.show_essay', title=t, page=1) }}">{{ t }}</a>
					{% endfor %}
				</div>
			</div>
		</div>
		<br>
		<br>
	</div>
</div>
{% endblock %}

ozone/templates/show_message.html
{% extends "base.html" %}
{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-10 offset-sm-1 col-md-6 offset-md-3" style="border-bottom-left-radius: 3px;border-bottom-right-radius: 3px;">
			{% for message in messages %}
			{% if message.owner == "汪先森" %}
			<div class="card">
				<div class="card-header" style="background: linear-gradient(to right, rgba(135, 206, 250, 1), rgba(135, 206, 250, 0.6));">
					{{ message.owner }}({{ message.timestamp }})
				</div>
				<div class="card-body">
					<h5 class="card-text">{{ message.content|safe|my_str_filter }}</h5>
				</div>
			</div>
			{% elif message.owner == "小笨笨" %}
			<div class="card">
				<div class="card-header" style="background: linear-gradient(to right, rgba(255, 192, 203, 1), rgba(255, 192, 203, 0.6));">
					{{ message.owner }}({{ message.timestamp }})
				</div>
				<div class="card-body">
					<h5 class="card-text">{{ message.content|safe|my_str_filter }}</h5>
				</div>
			</div>
			{% else %}
			<li><em>No messages</em>
				{% endif %}
				<br>
				{% endfor %}

				<!--pagination-->
				<div class="d-flex justify-content-center">
					<ul class="pagination">
						<li class="page-item"><a class="page-link" href="{{ url_for('message.show_message', page=current_page-1) }}">&laquo;</a></li>
						{% for page in range(1, total_page + 1) %}
						{% if current_page == page %}
						<li class="page-item active"><a class="page-link" href="{{ url_for('message.show_message', page=page) }}">{{ page }}</a></li>
						{% else %}
						<li class="page-item"><a class="page-link" href="{{ url_for('message.show_message', page=page) }}">{{ page }}</a></li>
						{% endif %}
						{% endfor %}
						<li class="page-item"><a class="page-link" href="{{ url_for('message.show_message', page=current_page+1) }}">&raquo;</a></li>
					</ul>
				</div>
				<div class="card">
					<div class="card-body">
						<a href="{{ url_for('message.add_message') }}">留言板</a>
					</div>
				</div>
				<br>
				<br>
		</div>
	</div>
</div>
{% endblock %}

ozone/templates/update.html
{% extends "base.html" %}
{% block body %}

{% if old_message %}
<!-- message -->
<div class="container-fluid">
    <form action="{{ url_for('message.update', timestamp=timestamp) }}" method="post">
        {{ form.hidden_tag() }}
        <textarea class="form-control" name="content">{{ old_message.content }}</textarea>
        <button type="submit" class="btn btn-primary btn-lg float-right">提交</button>
        <a href="{{ url_for('main.manage', function='message') }}" class="btn btn-lg btn-danger float-right" role="button">撤销修改</a>
    </form>
</div>
{% elif old_essay %}
<!-- column -->
<div class="container-fluid">
    <form action="{{ url_for('column.update', timestamp=timestamp) }}" method="post">
        {{ form.hidden_tag() }}
        <input type="text" name="title" class="form-control" value="{{ old_essay.title }}">
        <textarea class="form-control" name="content">{{ old_essay.content }}</textarea>
        <button type="submit" class="btn btn-primary btn-lg float-right">提交</button>
        <a href="{{ url_for('main.manage', function='column') }}" class="btn btn-lg btn-danger float-right" role="button">撤销修改</a>
    </form>
</div>
{% endif %}
{% endblock %}